### ISSUE TITLE
ignore_images skips images altogether

### ISSUE THREAD

**Issue by azamatx** [Skraer/gulp-starter-kit#2]
This config should ignore images while optimizing, but should include the original (non-optimized) versions in the `dist` folder:
`"ignore_images": ["svg", "png"]`
Right now it just excludes images with given extensions. For example, when you include "svg" and "png" in your config, you expect that SVG and PNG files will be copied to your  `dist` without getting optimized. But script just doesn't copy any SVG and PNG files into the `dist` folder. Those extensions just get excluded from the process totally.

**Comment by Skraer** [comment]
Issue was resolved, it works now
